version: "2"

services:
  mysql:
    image: mariadb:10.10
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    networks:
      innet:     
        ipv4_address: 10.100.20.11
  ldap:
    image: ldap:sh
    hostname: ldap
    container_name: ldap
    expose:
      - "389"
    ports:
      - '389:389'   
    volumes:
      - ldap_data:/var/lib/ldap
    networks:
      innet:     
        ipv4_address: 10.100.20.12

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08.6}
    build:
      context: .
      args:
        SLURM_TAG: ${SLURM_TAG:-slurm-21-08-6-1}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql
      - ldap
    networks:
      innet:     
        ipv4_address: 10.100.20.13

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08.6}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
      - "8999"
    ports:
      - '8999:8999'
    depends_on:
      - "slurmdbd"
    networks:
      innet:     
        ipv4_address: 10.100.20.14

  c1:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08.6}
    command: ["slurmd"]
    hostname: c1
    privileged: true
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      innet:     
        ipv4_address: 10.100.20.15

  login:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08.6}
    command: ["slurmd"]
    privileged: true
    hostname: login
    container_name: login
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - /root/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
    expose:
      - "6818"
    ports:
      - '1022:22'
    depends_on:
      - "slurmctld"
    networks:
      innet:  
        ipv4_address: 10.100.20.16

networks:
  innet:  
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.20.0/24     #指定子网
          gateway: 10.100.20.1       #指定网关

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  ldap_data:
